import { Injectable } from '@nestjs/common';
import { ContractTemplateType } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

// The real BINGO+ business affiliation contract — transcribed from
// `apps/business/public/Contrato afiliacion negocios.docx`, with that document's `[VARIABLE]`
// placeholders translated to this service's `{{snake_case}}` token convention (see
// `apps/business/public/diccionario de variables contrato negocio.docx` for the source dictionary
// of what each one means and how it's filled). ContractsService.buildContractSnapshot resolves
// every token below except {{fecha_aceptacion}}/{{fecha_vigencia}}, which stay literal until
// ContractsService.sign() substitutes them at the actual moment of signature — everything else is
// knowable at generation time, those two are not.
export const DEFAULT_BUSINESS_CONTRACT_TEMPLATE = [
  'CONTRATO DE AFILIACIÓN Y USO DE LA PLATAFORMA BINGO+',
  'COMPARECIENTES',
  'Comparecen a la celebración del presente contrato, por una parte:',
  '{{razon_social_bingoplus}}, sociedad legalmente constituida conforme a las leyes de la República del Ecuador, con Registro Único de Contribuyentes (RUC) No. {{ruc_bingoplus}}, con domicilio en {{direccion_bingoplus}}, debidamente representada por {{representante_legal_bingoplus}}, en su calidad de Representante Legal, a quien en adelante y para los efectos del presente instrumento se denominará "BINGO+"; y,\nPor otra parte:\n{{razon_social_negocio}}, con {{tipo_identificacion_negocio}} No. {{numero_identificacion_negocio}}, con domicilio en {{domicilio_negocio}}, representado por {{representante_negocio}}, en su calidad de representante, a quien en adelante y para los efectos del presente instrumento se denominará "EL NEGOCIO".\nBINGO+ y EL NEGOCIO, conjuntamente denominados "las Partes", libre y voluntariamente, en pleno uso de su capacidad legal, convienen en celebrar el presente Contrato de Afiliación y Uso de la Plataforma BINGO+ (en adelante, el "Contrato"), al tenor de las siguientes cláusulas:',
  'CLÁUSULA PRIMERA.- OBJETO\nMediante el presente Contrato, BINGO+ concede a EL NEGOCIO acceso a la plataforma tecnológica BINGO+ para la publicación, promoción y, cuando corresponda, comercialización de productos, y/o para la publicación y promoción de servicios relacionados con mascotas.\nEL NEGOCIO podrá participar en BINGO+ bajo una o ambas de las siguientes modalidades:\n1.1. TIENDA\nEL NEGOCIO podrá publicar y comercializar productos a través de la sección Marketplace/Tiendas de BINGO+. Las ventas de productos realizadas mediante BINGO+ estarán sujetas a la comisión de Marketplace establecida en el Anexo Comercial.\n1.2. DIRECTORIO\nEL NEGOCIO podrá publicar su perfil comercial dentro del Directorio BINGO+, destinado a facilitar el descubrimiento de negocios que ofrecen servicios relacionados con mascotas. La participación en el Directorio estará sujeta al fee de Directorio establecido en el Anexo Comercial.\n1.3. TIENDA + DIRECTORIO\nEL NEGOCIO podrá contratar simultáneamente ambas modalidades. En tal caso, cada modalidad se regirá por sus respectivas condiciones económicas.',
  'CLÁUSULA SEGUNDA.- NATURALEZA DE LA RELACIÓN\nBINGO+ proporciona una plataforma tecnológica que facilita la conexión entre EL NEGOCIO y los usuarios de la plataforma.\nBINGO+ no adquiere la propiedad de los productos comercializados por EL NEGOCIO, ni fabrica, importa, almacena, prepara o modifica dichos productos. De igual manera, BINGO+ no presta directamente los servicios publicados por EL NEGOCIO.\nEL NEGOCIO mantiene independencia jurídica, comercial, administrativa y operativa respecto de BINGO+. El presente Contrato no constituye sociedad, franquicia, relación laboral, agencia, representación comercial general ni relación de dependencia entre las Partes.',
  'CLÁUSULA TERCERA.- CONDICIONES ECONÓMICAS\nLas condiciones económicas aplicables a EL NEGOCIO constarán exclusivamente en el Anexo Comercial, que forma parte integrante del presente Contrato. El Anexo Comercial determinará, según corresponda:\nLa modalidad contratada;\nEl fee de Directorio;\nLa periodicidad del fee;\nLa comisión aplicable a ventas de Marketplace;\nLa periodicidad de liquidación; y,\nEl medio de pago.\nCualquier condición económica adicional deberá constar expresamente en una modificación o adenda al Anexo Comercial.',
  'CLÁUSULA CUARTA.- COMISIÓN DE MARKETPLACE\nCuando EL NEGOCIO opere bajo la modalidad TIENDA, BINGO+ cobrará la comisión establecida en el Anexo Comercial por las ventas de productos realizadas mediante el Marketplace. La comisión será calculada sobre la base expresamente indicada en el Anexo Comercial.\nBINGO+ no cobrará comisión sobre los servicios ofrecidos por EL NEGOCIO a través del Directorio.\nCuando BINGO+ habilite mecanismos tecnológicos para que un cliente pueda pagar un servicio a través de la plataforma, el valor correspondiente al servicio pertenecerá a EL NEGOCIO, sin que ello genere una comisión porcentual a favor de BINGO+ sobre dicho servicio, salvo modificación expresa del Anexo Comercial.',
  'CLÁUSULA QUINTA.- FEE DE DIRECTORIO\nCuando EL NEGOCIO contrate la modalidad DIRECTORIO, pagará a BINGO+ el fee indicado en el Anexo Comercial. El fee remunera la presencia de EL NEGOCIO dentro del Directorio y las funcionalidades que BINGO+ habilite para dicha modalidad.\nEl pago del fee no garantiza un número determinado de clientes, reservas, ventas, contactos o conversiones.',
  'CLÁUSULA SEXTA.- LIQUIDACIÓN Y PAGO\nBINGO+ realizará la liquidación de los valores correspondientes a EL NEGOCIO con periodicidad quincenal. La liquidación reflejará, según corresponda, el siguiente cálculo:\n(+) Ventas realizadas\n(−) Comisión BINGO+\n(−) Reembolsos o devoluciones aplicables\n(−) Contracargos u otros ajustes válidamente aplicables\n(=) Valor neto a liquidar a EL NEGOCIO\nEl pago se realizará mediante depósito o transferencia bancaria a la cuenta registrada por EL NEGOCIO en BINGO+.\nEL NEGOCIO será responsable de proporcionar información bancaria correcta y actualizada. BINGO+ no será responsable por retrasos ocasionados por información bancaria incorrecta, cuentas bloqueadas, errores atribuibles a la institución financiera o circunstancias ajenas a BINGO+.',
  'CLÁUSULA SÉPTIMA.- IMPUESTOS Y OBLIGACIONES TRIBUTARIAS\nEL NEGOCIO será responsable de sus propias obligaciones tributarias, incluyendo, sin limitarse a, las relacionadas con:\nEmisión de comprobantes de venta;\nImpuesto al Valor Agregado (IVA);\nImpuesto a la Renta;\nRetenciones, cuando correspondan;\nDeclaraciones;\nRegistros contables; y,\nDemás obligaciones establecidas por la normativa tributaria aplicable.\nEl hecho de que BINGO+ facilite el procesamiento o recaudo de valores relacionados con una transacción no convierte dichos valores en ingresos propios de BINGO+.\nCuando BINGO+ recaude valores correspondientes a impuestos atribuibles a la operación de EL NEGOCIO, dichos valores serán identificados y entregados a EL NEGOCIO conforme al mecanismo de liquidación aplicable, sin perjuicio de las obligaciones de retención, percepción, facturación u otras que legalmente correspondan a cualquiera de las Partes.\nEL NEGOCIO reconoce que BINGO+ no puede modificar, eliminar ni transferir contractualmente las obligaciones tributarias que la legislación atribuya directamente a cada contribuyente.\nLos comprobantes de venta correspondientes a las operaciones de EL NEGOCIO deberán emitirse de conformidad con la normativa tributaria vigente y las disposiciones expedidas por el Servicio de Rentas Internas (SRI) en materia de comprobantes de venta, retención y documentos complementarios.',
  'CLÁUSULA OCTAVA.- RESPONSABILIDAD SOBRE PRODUCTOS\nEL NEGOCIO será exclusivamente responsable por la calidad, seguridad, legalidad, autenticidad, composición, conservación, almacenamiento, empaque, etiquetado, fecha de vencimiento, condiciones sanitarias, características, información y estado de los productos que comercialice a través de la plataforma.\nBINGO+ actúa como plataforma tecnológica y no realiza una inspección individual de cada producto comercializado. En consecuencia, BINGO+ no será responsable por defectos, deterioro, contaminación, vencimiento, adulteración, productos incorrectos, productos incompletos o cualquier otra circunstancia atribuible al producto o a EL NEGOCIO.\nLo anterior se entiende sin perjuicio de las responsabilidades que legalmente puedan corresponder a BINGO+ por sus propios actos y de los derechos irrenunciables de los consumidores reconocidos en la Ley Orgánica de Defensa del Consumidor y demás normativa ecuatoriana aplicable.',
  'CLÁUSULA NOVENA.- RESPONSABILIDAD SOBRE SERVICIOS\nEL NEGOCIO será responsable de la prestación de los servicios que publique en BINGO+, lo cual comprende la calidad, el cumplimiento de lo ofrecido, horarios, reservas, instalaciones, personal, permisos, licencias, habilitaciones, condiciones sanitarias, seguridad y el cumplimiento de la normativa aplicable.\nBINGO+ no garantiza el resultado de los servicios prestados por EL NEGOCIO.',
  'CLÁUSULA DÉCIMA.- INFORMACIÓN DEL NEGOCIO\nEL NEGOCIO deberá proporcionar información verdadera, completa y actualizada, incluyendo: razón social o nombre comercial; RUC o información tributaria aplicable; dirección; teléfono; correo electrónico; horarios; fotografías; descripción; productos; precios; inventario; servicios; información de contacto; e información bancaria.\nEL NEGOCIO deberá informar inmediatamente a BINGO+ cualquier cambio relevante en dicha información.',
  'CLÁUSULA DÉCIMA PRIMERA.- PROPIEDAD INTELECTUAL\nEL NEGOCIO conserva la titularidad de sus marcas, logotipos, fotografías y contenidos. EL NEGOCIO concede a BINGO+ una licencia de uso no exclusiva y gratuita, durante la vigencia de la relación contractual, para utilizar dichos materiales con el propósito de:\nPublicar el perfil de EL NEGOCIO;\nMostrar sus productos;\nPromocionar el negocio;\nGenerar contenido comercial;\nOperar el Marketplace;\nOperar el Directorio; y,\nRealizar campañas de BINGO+.\nEL NEGOCIO garantiza que cuenta con los derechos necesarios para proporcionar dichos contenidos.',
  'CLÁUSULA DÉCIMA SEGUNDA.- CONFIDENCIALIDAD\nLas Partes mantendrán confidencial toda información comercial, financiera, tecnológica, operativa o estratégica recibida con ocasión de la relación contractual.\nEsta obligación permanecerá vigente durante la relación contractual y por 5 años posteriores a su terminación, salvo que la ley exija un plazo diferente o que determinada información deba permanecer protegida por su naturaleza.',
  'CLÁUSULA DÉCIMA TERCERA.- PROTECCIÓN DE DATOS PERSONALES\nLas Partes se sujetarán a la Ley Orgánica de Protección de Datos Personales, su Reglamento y demás normativa ecuatoriana aplicable en la materia. Las obligaciones específicas relacionadas con datos personales se desarrollan en el documento denominado "Política de Privacidad y Tratamiento de Datos de BINGO+".\nCuando corresponda legalmente, las Partes celebrarán o incorporarán las condiciones contractuales necesarias para regular su relación como responsable, encargado, tercero o corresponsables del tratamiento. Cuando exista encargo de tratamiento, este se regulará mediante contrato escrito que contendrá, al menos, las instrucciones del responsable, la finalidad del tratamiento, las medidas de seguridad, el régimen de subcontratación, la atención de los derechos de los titulares y la devolución o eliminación de los datos al término del encargo.',
  'CLÁUSULA DÉCIMA CUARTA.- SUSPENSIÓN\nBINGO+ podrá suspender temporalmente la cuenta de EL NEGOCIO cuando exista:\nIncumplimiento contractual;\nFraude o sospecha razonable de fraude;\nInformación falsa;\nProductos prohibidos;\nIncumplimiento legal;\nRiesgo para los usuarios;\nIncumplimiento de pagos;\nReiteración de cancelaciones;\nUso indebido de la plataforma; o,\nIncumplimiento de las Políticas de Marketplace o de Directorio.',
  'CLÁUSULA DÉCIMA QUINTA.- TERMINACIÓN\nCualquiera de las Partes podrá dar por terminado el presente Contrato mediante notificación escrita remitida a la otra Parte con al menos treinta (30) días calendario de anticipación.\nBINGO+ podrá darlo por terminado de forma inmediata ante incumplimientos graves, fraude, actividad ilícita, riesgo para los usuarios, incumplimiento legal o vulneraciones graves de las políticas de la plataforma.\nLa terminación no extinguirá las obligaciones económicas generadas antes de la fecha efectiva de terminación.',
  'CLÁUSULA DÉCIMA SEXTA.- EFECTOS DE LA TERMINACIÓN\nUna vez terminada la relación contractual:\nSe desactivará el perfil de EL NEGOCIO;\nSe deshabilitarán sus publicaciones;\nDejarán de recibirse nuevas operaciones;\nSe procesarán las liquidaciones pendientes;\nSe atenderán los reembolsos pendientes;\nSe conservará la información que legalmente deba conservarse; y,\nSe aplicarán las disposiciones de protección de datos correspondientes.',
  'CLÁUSULA DÉCIMA SÉPTIMA.- NOTIFICACIONES\nLas comunicaciones entre las Partes podrán realizarse mediante:\nCorreo electrónico registrado;\nSistema de notificaciones de BINGO+;\nDomicilio registrado; u,\nOtros mecanismos electrónicos aceptados por las Partes.',
  'CLÁUSULA DÉCIMA OCTAVA.- CONTRATACIÓN ELECTRÓNICA\nLas Partes reconocen la validez de la contratación electrónica conforme a la legislación ecuatoriana, en particular la Ley de Comercio Electrónico, Firmas Electrónicas y Mensajes de Datos y el Código de Comercio, en virtud de los cuales los contratos pueden instrumentarse mediante mensajes de datos y no se les negará validez por haberse utilizado medios electrónicos.\nCuando BINGO+ utilice firma electrónica, esta tendrá los mismos efectos jurídicos que la firma manuscrita, en las condiciones previstas por la ley.\nBINGO+ podrá conservar evidencia de la contratación, incluyendo: identidad del usuario, fecha, hora, versión del Contrato, versión del Anexo Comercial, dirección IP, correo electrónico, registros de aceptación y firma electrónica, cuando corresponda.',
  'CLÁUSULA DÉCIMA NOVENA.- LEGISLACIÓN APLICABLE Y SOLUCIÓN DE CONTROVERSIAS\nEl presente Contrato se regirá por las leyes de la República del Ecuador.\nLas Partes procurarán resolver cualquier controversia mediante negociación directa y, cuando corresponda, mediación. De no alcanzarse un acuerdo, las Partes podrán acudir a los mecanismos de solución de controversias establecidos en la ley.',
  'CLÁUSULA VIGÉSIMA.- INTEGRIDAD CONTRACTUAL\nEl presente Contrato y su Anexo Comercial constituyen el acuerdo íntegro entre las Partes respecto de la afiliación comercial. Los Términos y Condiciones del Negocio y la Política de Privacidad y Tratamiento de Datos de BINGO+ regulan, respectivamente, el uso de la plataforma y el tratamiento de datos personales.',
  'CLÁUSULA VIGÉSIMA PRIMERA.- ACEPTACIÓN\nLas Partes declaran haber leído íntegramente el presente Contrato y su Anexo Comercial, y aceptan su contenido en todas sus partes, en fe de lo cual lo suscriben por medios electrónicos en la fecha {{fecha_aceptacion}}.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante Legal\n{{razon_social_bingoplus}}\nEL NEGOCIO\n{{representante_negocio}}\n{{calidad_representante_negocio}},\n{{razon_social_negocio}}',
  'ANEXO COMERCIAL\nAL CONTRATO DE AFILIACIÓN Y USO DE LA PLATAFORMA BINGO+\nEl presente Anexo Comercial forma parte integrante del Contrato de Afiliación y Uso de la Plataforma BINGO+ suscrito entre BINGO+ y EL NEGOCIO.',
  'DATOS DEL NEGOCIO\nNombre comercial: {{nombre_comercial_negocio}}\nRazón social: {{razon_social_negocio}}\nRUC / Cédula: {{tipo_identificacion_negocio}} No. {{numero_identificacion_negocio}}\nRepresentante: {{representante_negocio}}',
  '1. MODALIDAD CONTRATADA\n{{check_tienda}} Tienda\n{{check_directorio}} Directorio\n{{check_tienda_directorio}} Tienda + Directorio',
  '2. MARKETPLACE\nComisión BINGO+: {{comision_marketplace}} %\nBase de cálculo: Valor de la venta, sin impuestos\nÁmbito: Exclusivamente ventas de productos realizadas mediante el Marketplace BINGO+\nComisión sobre servicios: 0 %',
  '3. DIRECTORIO\nPlan Directorio: {{plan_directorio}}\nPeriodicidad: Mensual, a partir de la finalización del período de prueba o del período cubierto por el cupón redimido, según corresponda\nÁmbito: El fee corresponde exclusivamente a la participación de EL NEGOCIO en el Directorio',
  '4. LIQUIDACIÓN\nPeriodicidad: Quincenal\nMedio de pago: Depósito bancario o transferencia bancaria\nBanco: {{banco}}\nTipo de cuenta: {{tipo_cuenta}}\nNúmero de cuenta: {{numero_cuenta}}\nTitular: {{titular_cuenta}}',
  '5. VIGENCIA DEL ANEXO\nEl presente Anexo Comercial entrará en vigencia desde el {{fecha_vigencia}}. Cualquier modificación deberá ser aceptada por EL NEGOCIO mediante el mecanismo establecido por BINGO+ para tal efecto.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante Legal\n{{razon_social_bingoplus}}\nEL NEGOCIO\n{{representante_negocio}}\n{{calidad_representante_negocio}},\n{{razon_social_negocio}}',
].join('\n\n');

// The real BINGO+ rider contract — transcribed from `apps/rider/public/Contrato_Rider_BINGO+.docx`,
// same `[VARIABLE]` → `{{snake_case}}` token translation as the BUSINESS default above (see
// `apps/rider/public/Diccionario_Variables_Contrato_Rider_BINGO+.docx` for the source dictionary).
// RiderContractsService.buildContractSnapshot resolves every token except {{fecha_aceptacion}},
// left literal until RiderContractsService.sign() — the actual moment of signature isn't known any
// earlier.
export const DEFAULT_RIDER_CONTRACT_TEMPLATE = [
  'CONTRATO DE PRESTACIÓN DE SERVICIOS DE ENTREGA\nY USO DE LA PLATAFORMA BINGO+',
  'COMPARECIENTES',
  'Comparecen a la celebración del presente contrato, por una parte:',
  '{{razon_social_bingoplus}}, sociedad legalmente constituida conforme a las leyes de la República del Ecuador, con Registro Único de Contribuyentes (RUC) No. {{ruc_bingoplus}}, con domicilio en {{direccion_bingoplus}}, debidamente representada por {{representante_legal_bingoplus}}, en su calidad de Representante legal, a quien en adelante y para los efectos del presente instrumento se denominará "BINGO+"; y,\nPor otra parte:\n{{nombre_completo_rider}}, con {{tipo_identificacion_rider}} No. {{numero_identificacion_rider}}, con domicilio en {{domicilio_rider}}, teléfono {{telefono_rider}}, correo electrónico {{correo_rider}}, por sus propios derechos, a quien en adelante y para los efectos del presente instrumento se denominará "EL RIDER".\nBINGO+ y EL RIDER, conjuntamente denominados "las Partes", libre y voluntariamente, en pleno uso de su capacidad legal, convienen en celebrar el presente Contrato de Prestación de Servicios de Entrega y Uso de la Plataforma BINGO+ (en adelante, el "Contrato"), al tenor de las siguientes cláusulas:',
  'CLÁUSULA PRIMERA.- OBJETO\nMediante el presente Contrato, BINGO+ habilita a EL RIDER para utilizar la plataforma tecnológica BINGO+ con el objeto de recibir, aceptar, gestionar y ejecutar servicios de entrega de productos comercializados mediante la plataforma.\nEL RIDER podrá recibir ofertas de entrega a través de la aplicación y, de acuerdo con las funcionalidades disponibles, aceptar o rechazar dichas ofertas.\nUna vez aceptada una entrega, EL RIDER deberá realizar las actividades necesarias para:\nAcudir al establecimiento o punto de recogida;\nRecibir el pedido correspondiente;\nVerificar razonablemente su identificación y estado externo;\nCustodiar el pedido durante el traslado;\nTransportarlo hasta el destino indicado;\nEntregarlo al cliente o destinatario autorizado; y,\nRegistrar en la plataforma el resultado de la entrega.',
  'CLÁUSULA SEGUNDA.- NATURALEZA DE LA RELACIÓN\nBINGO+ proporciona una plataforma tecnológica que facilita la asignación, gestión, seguimiento y liquidación de servicios de entrega.\nEL RIDER presta sus servicios de manera independiente y será responsable de organizar los medios necesarios para realizar las entregas aceptadas.\nEl presente Contrato no constituye, por sí mismo, sociedad, asociación, franquicia, agencia, representación comercial general ni relación de dependencia laboral entre las Partes, sin perjuicio de la calificación jurídica que corresponda conforme a la legislación aplicable.\nEL RIDER podrá realizar actividades para terceros y prestar servicios adicionales por cuenta propia, siempre que ello no implique el incumplimiento de sus obligaciones con BINGO+.',
  'CLÁUSULA TERCERA.- REQUISITOS DEL RIDER\nEL RIDER deberá proporcionar información verdadera, completa y actualizada para su incorporación a BINGO+, incluyendo, según corresponda:\nNombre completo;\nDocumento de identificación;\nRUC o información tributaria aplicable;\nTeléfono;\nCorreo electrónico;\nDomicilio;\nInformación bancaria;\nInformación del vehículo;\nPlaca;\nLicencia de conducir, cuando corresponda;\nDocumentación exigida para la circulación y operación del vehículo; y,\nCualquier otra información razonablemente necesaria para la operación.\nEL RIDER deberá mantener vigente y actualizada dicha información durante toda la relación contractual.',
  'CLÁUSULA CUARTA.- ACCESO Y USO DE LA PLATAFORMA\nBINGO+ proporcionará a EL RIDER las credenciales necesarias para acceder a la plataforma. La cuenta asignada a EL RIDER es personal e intransferible.\nEL RIDER no podrá:\nCompartir sus credenciales;\nPermitir que otra persona opere utilizando su cuenta;\nRegistrar información falsa;\nManipular su ubicación;\nAlterar artificialmente los estados de una entrega;\nGenerar evidencias falsas; ni,\nUtilizar mecanismos destinados a obtener pagos o incentivos de manera fraudulenta.',
  'CLÁUSULA QUINTA.- ASIGNACIÓN Y ACEPTACIÓN DE ENTREGAS\nBINGO+ podrá poner a disposición de EL RIDER ofertas de entrega mediante la plataforma. La asignación podrá considerar, entre otros criterios operativos:\nUbicación;\nDisponibilidad;\nDistancia;\nEstado del pedido;\nCapacidad operativa;\nTiempo estimado de llegada; y,\nOtros criterios tecnológicos utilizados por BINGO+.\nEL RIDER podrá aceptar o rechazar las ofertas de acuerdo con las funcionalidades habilitadas. Una vez aceptada una entrega, EL RIDER deberá cumplirla conforme a las instrucciones mostradas en la plataforma.',
  'CLÁUSULA SEXTA.- RETIRO Y CUSTODIA DE LOS PRODUCTOS\nDesde el momento en que EL RIDER recibe un producto del establecimiento y hasta su entrega al destinatario o su devolución al establecimiento indicado, EL RIDER tendrá la obligación de ejercer una custodia diligente sobre dicho producto. En consecuencia, EL RIDER deberá:\nManipular el pedido con cuidado;\nTransportarlo utilizando medios adecuados;\nEvitar golpes, caídas, contaminación o exposición innecesaria;\nNo abrir ni manipular el contenido del pedido;\nNo sustituir productos;\nNo consumir productos;\nNo disponer de los productos; y,\nSeguir las instrucciones razonables de transporte proporcionadas por la plataforma o el establecimiento.',
  'CLÁUSULA SÉPTIMA.- DAÑO, PÉRDIDA, FALTANTE O DETERIORO\nSi durante el período en que el producto se encuentre bajo custodia de EL RIDER se produce una pérdida, sustracción, daño, faltante, apertura, contaminación, deterioro o cualquier otra afectación del producto, BINGO+ podrá iniciar una revisión del incidente.\nCuando, mediante evidencia suficiente, se determine que el daño, pérdida, faltante o deterioro es imputable a EL RIDER por acción, omisión, negligencia, incumplimiento de las instrucciones de transporte o conducta indebida, BINGO+ podrá:\nSolicitar a EL RIDER el reembolso del valor correspondiente; o,\nCompensar el valor comprobado con valores pendientes de pago a favor de EL RIDER, hasta el límite permitido por la legislación aplicable.\nAntes de aplicar una compensación por daño o pérdida atribuible, BINGO+ deberá comunicar el incidente a EL RIDER y permitirle presentar las explicaciones o evidencias que considere pertinentes. No se realizará descuento automático alguno por la sola existencia de una reclamación.\nCuando el valor comprobado sea superior a los valores pendientes de pago, BINGO+ podrá solicitar a EL RIDER el reembolso del saldo correspondiente.\nLo dispuesto en la presente cláusula no aplicará cuando el daño o la pérdida sea consecuencia de circunstancias no imputables a EL RIDER.',
  'CLÁUSULA OCTAVA.- ENTREGA AL CLIENTE\nEL RIDER deberá entregar el pedido exclusivamente al destinatario autorizado, conforme a las instrucciones de la plataforma. BINGO+ podrá utilizar mecanismos de verificación tales como:\nCódigo de verificación de un solo uso (OTP);\nConfirmación dentro de la aplicación;\nFotografía;\nFirma;\nRegistro de ubicación;\nFecha y hora; u,\nOtros mecanismos tecnológicos.\nEL RIDER no deberá entregar el pedido a una persona distinta del destinatario autorizado, salvo instrucción expresa recibida mediante los canales establecidos.',
  'CLÁUSULA NOVENA.- ENTREGA FALLIDA Y DEVOLUCIÓN\nCuando EL RIDER no pueda completar una entrega, deberá registrar inmediatamente la incidencia en la plataforma y seguir las instrucciones correspondientes.\nCuando sea necesario devolver el pedido al establecimiento, EL RIDER deberá conservarlo adecuadamente hasta completar la devolución.\nEL RIDER no podrá abandonar, desechar, abrir, vender, consumir ni disponer del producto correspondiente a una entrega fallida.',
  'CLÁUSULA DÉCIMA.- PAGOS Y COMISIONES DEL RIDER\nBINGO+ pagará a EL RIDER los valores, tarifas, comisiones o incentivos correspondientes a los servicios de entrega realizados, conforme al esquema económico establecido en el Anexo Operativo. Las condiciones económicas aplicables podrán incluir:\nValor por entrega;\nPropinas y\nOtros conceptos expresamente comunicados por BINGO+.\nLa liquidación se realizará con la periodicidad establecida en el Anexo Operativo y mediante el medio de pago registrado por EL RIDER.\nBINGO+ podrá efectuar ajustes sobre las liquidaciones cuando existan pagos duplicados, operaciones fraudulentas, cancelaciones, contracargos, errores de liquidación o pérdidas y daños imputables a EL RIDER, conforme al presente Contrato y a la legislación aplicable.',
  'CLÁUSULA DÉCIMA PRIMERA.- OBLIGACIONES TRIBUTARIAS\nEL RIDER será responsable de sus propias obligaciones tributarias derivadas de los ingresos obtenidos por su actividad, las cuales podrán incluir, según corresponda:\nRegistro tributario;\nEmisión de comprobantes de venta;\nDeclaraciones;\nImpuesto a la Renta;\nImpuesto al Valor Agregado (IVA);\nRetenciones; y,\nLas demás obligaciones establecidas por la normativa aplicable.\nBINGO+ podrá efectuar las retenciones que legalmente correspondan. El pago de valores a EL RIDER por parte de BINGO+ no transfiere a BINGO+ las obligaciones tributarias que legalmente correspondan a EL RIDER.',
  'CLÁUSULA DÉCIMA SEGUNDA.- VEHÍCULO, LICENCIA Y SEGURIDAD VIAL\nEL RIDER será responsable de utilizar un vehículo adecuado para realizar las entregas y de mantenerlo en condiciones razonables de funcionamiento y seguridad. Cuando corresponda, deberá mantener vigentes:\nLicencia de conducir;\nMatrícula;\nRevisión técnica vehicular;\nSeguro o documentación exigible;\nPermisos correspondientes; y,\nElementos de seguridad exigidos por la normativa.\nEL RIDER deberá cumplir las normas de tránsito aplicables durante la ejecución de los servicios.',
  'CLÁUSULA DÉCIMA TERCERA.- ACCIDENTES E INCIDENTES\nEL RIDER deberá informar oportunamente a BINGO+ cualquier:\nAccidente;\nRobo;\nPérdida de productos;\nDaño de productos;\nAgresión;\nIncidente de seguridad;\nProblema con el vehículo; o,\nCircunstancia que pueda impedir completar una entrega.\nBINGO+ podrá solicitar evidencia y documentación relacionada con el incidente.',
  'CLÁUSULA DÉCIMA CUARTA.- PROHIBICIONES\nSe prohíbe a EL RIDER:\nAbrir los productos transportados;\nConsumir productos;\nSustituir productos;\nApropiarse de productos;\nUtilizar productos para fines personales;\nManipular artificialmente su ubicación;\nFalsificar evidencias de entrega;\nCompartir su cuenta;\nPermitir que terceros realicen entregas utilizando su cuenta;\nUtilizar información de clientes para fines personales;\nContactar posteriormente a clientes para fines comerciales no autorizados;\nAlterar pedidos;\nGenerar entregas fraudulentas; o,\nRealizar cualquier actividad ilícita mediante la plataforma.',
  'CLÁUSULA DÉCIMA QUINTA.- PROTECCIÓN DE DATOS PERSONALES\nEL RIDER podrá acceder a determinados datos personales de clientes y negocios necesarios para ejecutar las entregas. Dicha información podrá incluir, según corresponda:\nNombre;\nNúmero telefónico;\nDirección;\nUbicación;\nReferencias para la entrega; e,\nInformación relacionada con el pedido.\nEL RIDER únicamente podrá utilizar dichos datos para ejecutar la entrega y resolver incidencias relacionadas con ella, y no podrá copiarlos, almacenarlos, venderlos, divulgarlos, transferirlos ni utilizarlos para finalidades personales o comerciales ajenas a la operación.\nLas Partes se sujetarán a la Ley Orgánica de Protección de Datos Personales, su Reglamento y demás normativa aplicable. Las obligaciones específicas sobre protección de datos se desarrollan en la Política de Privacidad y Tratamiento de Datos Personales de BINGO+ para Riders.',
  'CLÁUSULA DÉCIMA SEXTA.- PROPIEDAD INTELECTUAL\nBINGO+ conserva la titularidad de la plataforma, software, aplicaciones, marcas, diseños, interfaces, contenidos y demás elementos tecnológicos.\nEL RIDER recibe únicamente una autorización de uso limitada, personal y no transferible para utilizar la plataforma durante la vigencia de su relación con BINGO+.',
  'CLÁUSULA DÉCIMA SÉPTIMA.- CONFIDENCIALIDAD\nEL RIDER deberá mantener confidencial toda información comercial, operativa, tecnológica, financiera o personal a la que tenga acceso como consecuencia de su relación con BINGO+.\nEsta obligación permanecerá vigente durante la relación contractual y después de su terminación, respecto de la información que mantenga carácter confidencial o cuya protección sea exigida por la ley.',
  'CLÁUSULA DÉCIMA OCTAVA.- SUSPENSIÓN\nBINGO+ podrá suspender temporalmente la cuenta de EL RIDER cuando exista:\nIncumplimiento contractual;\nFraude o sospecha razonable de fraude;\nInformación falsa;\nDocumentación vencida;\nIncumplimiento de normas de tránsito;\nDaño o pérdida atribuible a EL RIDER;\nUso indebido de datos personales;\nRiesgo para clientes, negocios u otros riders;\nManipulación de la plataforma;\nActividad ilícita; o,\nRequerimiento de autoridad competente.\nLa suspensión podrá mantenerse durante el período necesario para investigar el incidente, adoptar medidas de seguridad o verificar documentación.',
  'CLÁUSULA DÉCIMA NOVENA.- TERMINACIÓN\nCualquiera de las Partes podrá dar por terminado el presente Contrato mediante notificación a la otra Parte.\nBINGO+ podrá darlo por terminado de manera inmediata ante incumplimientos graves, fraude, apropiación o pérdida intencional de productos, actividad ilícita, uso indebido de datos, riesgos graves para los usuarios o incumplimiento legal.\nLa terminación no extinguirá las obligaciones económicas, tributarias, de confidencialidad, de protección de datos o de responsabilidad generadas durante la vigencia del Contrato.',
  'CLÁUSULA VIGÉSIMA.- EFECTOS DE LA TERMINACIÓN\nUna vez terminada la relación contractual:\nSe desactivará la cuenta de EL RIDER;\nSe suspenderá la posibilidad de aceptar nuevas entregas;\nSe procesarán los valores pendientes;\nSe realizarán los ajustes válidamente aplicables;\nSe resolverán los incidentes pendientes;\nSe conservará la información que legalmente deba conservarse; y,\nSe aplicarán las disposiciones correspondientes de protección de datos.',
  'CLÁUSULA VIGÉSIMA PRIMERA.- CONTRATACIÓN ELECTRÓNICA\nLas Partes reconocen la validez de la contratación electrónica conforme a la legislación ecuatoriana, en particular la Ley de Comercio Electrónico, Firmas Electrónicas y Mensajes de Datos y el Código de Comercio. BINGO+ podrá conservar evidencia de:\nIdentidad de EL RIDER;\nFecha;\nHora;\nVersión del Contrato;\nDirección IP;\nCorreo electrónico;\nRegistro de aceptación;\nRegistro de firma; y,\nDemás información técnica disponible.',
  'CLÁUSULA VIGÉSIMA SEGUNDA.- LEGISLACIÓN APLICABLE Y SOLUCIÓN DE CONTROVERSIAS\nEl presente Contrato se regirá por las leyes de la República del Ecuador.\nLas Partes procurarán resolver cualquier controversia mediante negociación directa y, cuando corresponda, mediación. De no alcanzarse un acuerdo, las Partes podrán acudir a los mecanismos de solución de controversias establecidos en la legislación aplicable.',
  'CLÁUSULA VIGÉSIMA TERCERA.- INTEGRIDAD CONTRACTUAL\nEl presente Contrato y su Anexo Operativo constituyen el acuerdo íntegro entre las Partes respecto de la prestación de servicios de entrega.\nLos Términos y Condiciones de Uso de la Plataforma para Riders y la Política de Privacidad y Tratamiento de Datos Personales para Riders regulan, respectivamente, el uso de la plataforma y el tratamiento de datos personales.',
  'CLÁUSULA VIGÉSIMA CUARTA.- ACEPTACIÓN\nEL RIDER declara haber leído íntegramente el presente Contrato y su Anexo Operativo, y acepta su contenido mediante el mecanismo electrónico habilitado por BINGO+, en la fecha {{fecha_aceptacion}}.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante legal\n{{razon_social_bingoplus}}\nEL RIDER\n{{nombre_completo_rider}}\n{{tipo_identificacion_rider}} No. {{numero_identificacion_rider}}',
  'ANEXO OPERATIVO\nAL CONTRATO DE PRESTACIÓN DE SERVICIOS DE ENTREGA Y USO DE LA PLATAFORMA BINGO+\nEl presente Anexo Operativo forma parte integrante del Contrato de Prestación de Servicios de Entrega y Uso de la Plataforma BINGO+ celebrado entre BINGO+ y EL RIDER.',
  'DATOS DEL RIDER\nNombre completo: {{nombre_completo_rider}}\nTipo de identificación: {{tipo_identificacion_rider}}\nNúmero de identificación: {{numero_identificacion_rider}}\nTeléfono: {{telefono_rider}}\nCorreo electrónico: {{correo_rider}}\nDomicilio: {{domicilio_rider}}\nBanco: {{banco}}\nTipo de cuenta: {{tipo_cuenta}}\nNúmero de cuenta: {{numero_cuenta}}\nTitular de la cuenta: {{titular_cuenta}}',
  '1. INFORMACIÓN DEL VEHÍCULO\nTipo de vehículo: {{tipo_vehiculo}}\nColor: {{color_vehiculo}}\nMarca: {{marca_vehiculo}}\nModelo: {{modelo_vehiculo}}\nAño: {{anio_vehiculo}}\nPlaca: {{placa}}\nLicencia de conducir No.: {{numero_licencia}}\nVigencia de la licencia: {{vigencia_licencia}}',
  '2. CONDICIONES ECONÓMICAS\nComisión BINGO+ sobre el delivery: {{comision_bingo_delivery}} %\nValor para EL RIDER: {{comision_rider}} %\nPropinas: 100 % a favor de EL RIDER\nPeriodicidad de liquidación: Quincenal\nMedio de pago: Depósito o transferencia bancaria a la cuenta registrada\nLas tarifas variables podrán ser modificadas por BINGO+ de conformidad con las reglas y los mecanismos de comunicación aplicables.',
  '3. VIGENCIA DEL ANEXO\nEl presente Anexo Operativo entrará en vigencia desde el {{fecha_aceptacion}}.\nCualquier modificación de las condiciones contractuales deberá ser aceptada por EL RIDER mediante el mecanismo establecido por BINGO+, cuando ello sea legalmente requerido.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante legal\n{{razon_social_bingoplus}}\nEL RIDER\n{{nombre_completo_rider}}\n{{tipo_identificacion_rider}} No. {{numero_identificacion_rider}}',
].join('\n\n');

/**
 * Admin-editable contract template text (append-only, latest wins — same shape as
 * PricingConfigService). ContractsService/RiderContractsService read the latest template at
 * contract-GENERATION time and substitute its {{...}} placeholder tokens with that business/
 * rider's actual live figures; the result is frozen onto the contract row itself, so editing the
 * template here never changes a contract someone already signed (see BusinessContract.contractText/
 * RiderContract.contractText).
 */
@Injectable()
export class ContractTemplateService {
  constructor(private readonly prisma: PrismaService) {}

  async get(type: ContractTemplateType): Promise<string> {
    const row = await this.prisma.contractTemplate.findFirst({ where: { type }, orderBy: { createdAt: 'desc' } });
    if (row) return row.content;
    return type === ContractTemplateType.BUSINESS ? DEFAULT_BUSINESS_CONTRACT_TEMPLATE : DEFAULT_RIDER_CONTRACT_TEMPLATE;
  }

  async set(type: ContractTemplateType, content: string, updatedBy?: string): Promise<string> {
    await this.prisma.contractTemplate.create({ data: { type, content, updatedBy } });
    return content;
  }
}
