import { Injectable } from '@nestjs/common';
import { ContractTemplateType } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';

// The real BINGO+ business affiliation contract — transcribed from
// `apps/business/public/Contrato afiliacion negocios.docx`, with that document's `[VARIABLE]`
// placeholders translated to this service's `{{snake_case}}` token convention (see
// `apps/business/public/diccionario de variables contrato negocio.docx` for the source dictionary
// of what each one means and how it's filled). ContractsService.buildContractSnapshot resolves
// every token below except {{fecha_aceptacion}}/{{fecha_vigencia}}, which stay literal until
// ContractsService.sign() substitutes them at the actual moment of signature — everything else is
// knowable at generation time, those two are not.
export const DEFAULT_BUSINESS_CONTRACT_TEMPLATE = [
  'CONTRATO DE AFILIACIÓN Y USO DE LA PLATAFORMA BINGO+',
  'COMPARECIENTES',
  'Comparecen a la celebración del presente contrato, por una parte:',
  '{{razon_social_bingoplus}}, sociedad legalmente constituida conforme a las leyes de la República del Ecuador, con Registro Único de Contribuyentes (RUC) No. {{ruc_bingoplus}}, con domicilio en {{direccion_bingoplus}}, debidamente representada por {{representante_legal_bingoplus}}, en su calidad de Representante Legal, a quien en adelante y para los efectos del presente instrumento se denominará "BINGO+"; y,\nPor otra parte:\n{{razon_social_negocio}}, con {{tipo_identificacion_negocio}} No. {{numero_identificacion_negocio}}, con domicilio en {{domicilio_negocio}}, representado por {{representante_negocio}}, en su calidad de representante, a quien en adelante y para los efectos del presente instrumento se denominará "EL NEGOCIO".\nBINGO+ y EL NEGOCIO, conjuntamente denominados "las Partes", libre y voluntariamente, en pleno uso de su capacidad legal, convienen en celebrar el presente Contrato de Afiliación y Uso de la Plataforma BINGO+ (en adelante, el "Contrato"), al tenor de las siguientes cláusulas:',
  'CLÁUSULA PRIMERA.- OBJETO\nMediante el presente Contrato, BINGO+ concede a EL NEGOCIO acceso a la plataforma tecnológica BINGO+ para la publicación, promoción y, cuando corresponda, comercialización de productos, y/o para la publicación y promoción de servicios relacionados con mascotas.\nEL NEGOCIO podrá participar en BINGO+ bajo una o ambas de las siguientes modalidades:\n1.1. TIENDA\nEL NEGOCIO podrá publicar y comercializar productos a través de la sección Marketplace/Tiendas de BINGO+. Las ventas de productos realizadas mediante BINGO+ estarán sujetas a la comisión de Marketplace establecida en el Anexo Comercial.\n1.2. DIRECTORIO\nEL NEGOCIO podrá publicar su perfil comercial dentro del Directorio BINGO+, destinado a facilitar el descubrimiento de negocios que ofrecen servicios relacionados con mascotas. La participación en el Directorio estará sujeta al fee de Directorio establecido en el Anexo Comercial.\n1.3. TIENDA + DIRECTORIO\nEL NEGOCIO podrá contratar simultáneamente ambas modalidades. En tal caso, cada modalidad se regirá por sus respectivas condiciones económicas.',
  'CLÁUSULA SEGUNDA.- NATURALEZA DE LA RELACIÓN\nBINGO+ proporciona una plataforma tecnológica que facilita la conexión entre EL NEGOCIO y los usuarios de la plataforma.\nBINGO+ no adquiere la propiedad de los productos comercializados por EL NEGOCIO, ni fabrica, importa, almacena, prepara o modifica dichos productos. De igual manera, BINGO+ no presta directamente los servicios publicados por EL NEGOCIO.\nEL NEGOCIO mantiene independencia jurídica, comercial, administrativa y operativa respecto de BINGO+. El presente Contrato no constituye sociedad, franquicia, relación laboral, agencia, representación comercial general ni relación de dependencia entre las Partes.',
  'CLÁUSULA TERCERA.- CONDICIONES ECONÓMICAS\nLas condiciones económicas aplicables a EL NEGOCIO constarán exclusivamente en el Anexo Comercial, que forma parte integrante del presente Contrato. El Anexo Comercial determinará, según corresponda:\nLa modalidad contratada;\nEl fee de Directorio;\nLa periodicidad del fee;\nLa comisión aplicable a ventas de Marketplace;\nLa periodicidad de liquidación; y,\nEl medio de pago.\nCualquier condición económica adicional deberá constar expresamente en una modificación o adenda al Anexo Comercial.',
  'CLÁUSULA CUARTA.- COMISIÓN DE MARKETPLACE\nCuando EL NEGOCIO opere bajo la modalidad TIENDA, BINGO+ cobrará la comisión establecida en el Anexo Comercial por las ventas de productos realizadas mediante el Marketplace. La comisión será calculada sobre la base expresamente indicada en el Anexo Comercial.\nBINGO+ no cobrará comisión sobre los servicios ofrecidos por EL NEGOCIO a través del Directorio.\nCuando BINGO+ habilite mecanismos tecnológicos para que un cliente pueda pagar un servicio a través de la plataforma, el valor correspondiente al servicio pertenecerá a EL NEGOCIO, sin que ello genere una comisión porcentual a favor de BINGO+ sobre dicho servicio, salvo modificación expresa del Anexo Comercial.',
  'CLÁUSULA QUINTA.- FEE DE DIRECTORIO\nCuando EL NEGOCIO contrate la modalidad DIRECTORIO, pagará a BINGO+ el fee indicado en el Anexo Comercial. El fee remunera la presencia de EL NEGOCIO dentro del Directorio y las funcionalidades que BINGO+ habilite para dicha modalidad.\nEl pago del fee no garantiza un número determinado de clientes, reservas, ventas, contactos o conversiones.',
  'CLÁUSULA SEXTA.- LIQUIDACIÓN Y PAGO\nBINGO+ realizará la liquidación de los valores correspondientes a EL NEGOCIO con periodicidad quincenal. La liquidación reflejará, según corresponda, el siguiente cálculo:\n(+) Ventas realizadas\n(−) Comisión BINGO+\n(−) Reembolsos o devoluciones aplicables\n(−) Contracargos u otros ajustes válidamente aplicables\n(=) Valor neto a liquidar a EL NEGOCIO\nEl pago se realizará mediante depósito o transferencia bancaria a la cuenta registrada por EL NEGOCIO en BINGO+.\nEL NEGOCIO será responsable de proporcionar información bancaria correcta y actualizada. BINGO+ no será responsable por retrasos ocasionados por información bancaria incorrecta, cuentas bloqueadas, errores atribuibles a la institución financiera o circunstancias ajenas a BINGO+.',
  'CLÁUSULA SÉPTIMA.- IMPUESTOS Y OBLIGACIONES TRIBUTARIAS\nEL NEGOCIO será responsable de sus propias obligaciones tributarias, incluyendo, sin limitarse a, las relacionadas con:\nEmisión de comprobantes de venta;\nImpuesto al Valor Agregado (IVA);\nImpuesto a la Renta;\nRetenciones, cuando correspondan;\nDeclaraciones;\nRegistros contables; y,\nDemás obligaciones establecidas por la normativa tributaria aplicable.\nEl hecho de que BINGO+ facilite el procesamiento o recaudo de valores relacionados con una transacción no convierte dichos valores en ingresos propios de BINGO+.\nCuando BINGO+ recaude valores correspondientes a impuestos atribuibles a la operación de EL NEGOCIO, dichos valores serán identificados y entregados a EL NEGOCIO conforme al mecanismo de liquidación aplicable, sin perjuicio de las obligaciones de retención, percepción, facturación u otras que legalmente correspondan a cualquiera de las Partes.\nEL NEGOCIO reconoce que BINGO+ no puede modificar, eliminar ni transferir contractualmente las obligaciones tributarias que la legislación atribuya directamente a cada contribuyente.\nLos comprobantes de venta correspondientes a las operaciones de EL NEGOCIO deberán emitirse de conformidad con la normativa tributaria vigente y las disposiciones expedidas por el Servicio de Rentas Internas (SRI) en materia de comprobantes de venta, retención y documentos complementarios.',
  'CLÁUSULA OCTAVA.- RESPONSABILIDAD SOBRE PRODUCTOS\nEL NEGOCIO será exclusivamente responsable por la calidad, seguridad, legalidad, autenticidad, composición, conservación, almacenamiento, empaque, etiquetado, fecha de vencimiento, condiciones sanitarias, características, información y estado de los productos que comercialice a través de la plataforma.\nBINGO+ actúa como plataforma tecnológica y no realiza una inspección individual de cada producto comercializado. En consecuencia, BINGO+ no será responsable por defectos, deterioro, contaminación, vencimiento, adulteración, productos incorrectos, productos incompletos o cualquier otra circunstancia atribuible al producto o a EL NEGOCIO.\nLo anterior se entiende sin perjuicio de las responsabilidades que legalmente puedan corresponder a BINGO+ por sus propios actos y de los derechos irrenunciables de los consumidores reconocidos en la Ley Orgánica de Defensa del Consumidor y demás normativa ecuatoriana aplicable.',
  'CLÁUSULA NOVENA.- RESPONSABILIDAD SOBRE SERVICIOS\nEL NEGOCIO será responsable de la prestación de los servicios que publique en BINGO+, lo cual comprende la calidad, el cumplimiento de lo ofrecido, horarios, reservas, instalaciones, personal, permisos, licencias, habilitaciones, condiciones sanitarias, seguridad y el cumplimiento de la normativa aplicable.\nBINGO+ no garantiza el resultado de los servicios prestados por EL NEGOCIO.',
  'CLÁUSULA DÉCIMA.- INFORMACIÓN DEL NEGOCIO\nEL NEGOCIO deberá proporcionar información verdadera, completa y actualizada, incluyendo: razón social o nombre comercial; RUC o información tributaria aplicable; dirección; teléfono; correo electrónico; horarios; fotografías; descripción; productos; precios; inventario; servicios; información de contacto; e información bancaria.\nEL NEGOCIO deberá informar inmediatamente a BINGO+ cualquier cambio relevante en dicha información.',
  'CLÁUSULA DÉCIMA PRIMERA.- PROPIEDAD INTELECTUAL\nEL NEGOCIO conserva la titularidad de sus marcas, logotipos, fotografías y contenidos. EL NEGOCIO concede a BINGO+ una licencia de uso no exclusiva y gratuita, durante la vigencia de la relación contractual, para utilizar dichos materiales con el propósito de:\nPublicar el perfil de EL NEGOCIO;\nMostrar sus productos;\nPromocionar el negocio;\nGenerar contenido comercial;\nOperar el Marketplace;\nOperar el Directorio; y,\nRealizar campañas de BINGO+.\nEL NEGOCIO garantiza que cuenta con los derechos necesarios para proporcionar dichos contenidos.',
  'CLÁUSULA DÉCIMA SEGUNDA.- CONFIDENCIALIDAD\nLas Partes mantendrán confidencial toda información comercial, financiera, tecnológica, operativa o estratégica recibida con ocasión de la relación contractual.\nEsta obligación permanecerá vigente durante la relación contractual y por 5 años posteriores a su terminación, salvo que la ley exija un plazo diferente o que determinada información deba permanecer protegida por su naturaleza.',
  'CLÁUSULA DÉCIMA TERCERA.- PROTECCIÓN DE DATOS PERSONALES\nLas Partes se sujetarán a la Ley Orgánica de Protección de Datos Personales, su Reglamento y demás normativa ecuatoriana aplicable en la materia. Las obligaciones específicas relacionadas con datos personales se desarrollan en el documento denominado "Política de Privacidad y Tratamiento de Datos de BINGO+".\nCuando corresponda legalmente, las Partes celebrarán o incorporarán las condiciones contractuales necesarias para regular su relación como responsable, encargado, tercero o corresponsables del tratamiento. Cuando exista encargo de tratamiento, este se regulará mediante contrato escrito que contendrá, al menos, las instrucciones del responsable, la finalidad del tratamiento, las medidas de seguridad, el régimen de subcontratación, la atención de los derechos de los titulares y la devolución o eliminación de los datos al término del encargo.',
  'CLÁUSULA DÉCIMA CUARTA.- SUSPENSIÓN\nBINGO+ podrá suspender temporalmente la cuenta de EL NEGOCIO cuando exista:\nIncumplimiento contractual;\nFraude o sospecha razonable de fraude;\nInformación falsa;\nProductos prohibidos;\nIncumplimiento legal;\nRiesgo para los usuarios;\nIncumplimiento de pagos;\nReiteración de cancelaciones;\nUso indebido de la plataforma; o,\nIncumplimiento de las Políticas de Marketplace o de Directorio.',
  'CLÁUSULA DÉCIMA QUINTA.- TERMINACIÓN\nCualquiera de las Partes podrá dar por terminado el presente Contrato mediante notificación escrita remitida a la otra Parte con al menos treinta (30) días calendario de anticipación.\nBINGO+ podrá darlo por terminado de forma inmediata ante incumplimientos graves, fraude, actividad ilícita, riesgo para los usuarios, incumplimiento legal o vulneraciones graves de las políticas de la plataforma.\nLa terminación no extinguirá las obligaciones económicas generadas antes de la fecha efectiva de terminación.',
  'CLÁUSULA DÉCIMA SEXTA.- EFECTOS DE LA TERMINACIÓN\nUna vez terminada la relación contractual:\nSe desactivará el perfil de EL NEGOCIO;\nSe deshabilitarán sus publicaciones;\nDejarán de recibirse nuevas operaciones;\nSe procesarán las liquidaciones pendientes;\nSe atenderán los reembolsos pendientes;\nSe conservará la información que legalmente deba conservarse; y,\nSe aplicarán las disposiciones de protección de datos correspondientes.',
  'CLÁUSULA DÉCIMA SÉPTIMA.- NOTIFICACIONES\nLas comunicaciones entre las Partes podrán realizarse mediante:\nCorreo electrónico registrado;\nSistema de notificaciones de BINGO+;\nDomicilio registrado; u,\nOtros mecanismos electrónicos aceptados por las Partes.',
  'CLÁUSULA DÉCIMA OCTAVA.- CONTRATACIÓN ELECTRÓNICA\nLas Partes reconocen la validez de la contratación electrónica conforme a la legislación ecuatoriana, en particular la Ley de Comercio Electrónico, Firmas Electrónicas y Mensajes de Datos y el Código de Comercio, en virtud de los cuales los contratos pueden instrumentarse mediante mensajes de datos y no se les negará validez por haberse utilizado medios electrónicos.\nCuando BINGO+ utilice firma electrónica, esta tendrá los mismos efectos jurídicos que la firma manuscrita, en las condiciones previstas por la ley.\nBINGO+ podrá conservar evidencia de la contratación, incluyendo: identidad del usuario, fecha, hora, versión del Contrato, versión del Anexo Comercial, dirección IP, correo electrónico, registros de aceptación y firma electrónica, cuando corresponda.',
  'CLÁUSULA DÉCIMA NOVENA.- LEGISLACIÓN APLICABLE Y SOLUCIÓN DE CONTROVERSIAS\nEl presente Contrato se regirá por las leyes de la República del Ecuador.\nLas Partes procurarán resolver cualquier controversia mediante negociación directa y, cuando corresponda, mediación. De no alcanzarse un acuerdo, las Partes podrán acudir a los mecanismos de solución de controversias establecidos en la ley.',
  'CLÁUSULA VIGÉSIMA.- INTEGRIDAD CONTRACTUAL\nEl presente Contrato y su Anexo Comercial constituyen el acuerdo íntegro entre las Partes respecto de la afiliación comercial. Los Términos y Condiciones del Negocio y la Política de Privacidad y Tratamiento de Datos de BINGO+ regulan, respectivamente, el uso de la plataforma y el tratamiento de datos personales.',
  'CLÁUSULA VIGÉSIMA PRIMERA.- ACEPTACIÓN\nLas Partes declaran haber leído íntegramente el presente Contrato y su Anexo Comercial, y aceptan su contenido en todas sus partes, en fe de lo cual lo suscriben por medios electrónicos en la fecha {{fecha_aceptacion}}.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante Legal\n{{razon_social_bingoplus}}\nEL NEGOCIO\n{{representante_negocio}}\n{{calidad_representante_negocio}},\n{{razon_social_negocio}}',
  'ANEXO COMERCIAL\nAL CONTRATO DE AFILIACIÓN Y USO DE LA PLATAFORMA BINGO+\nEl presente Anexo Comercial forma parte integrante del Contrato de Afiliación y Uso de la Plataforma BINGO+ suscrito entre BINGO+ y EL NEGOCIO.',
  'DATOS DEL NEGOCIO\nNombre comercial: {{nombre_comercial_negocio}}\nRazón social: {{razon_social_negocio}}\nRUC / Cédula: {{tipo_identificacion_negocio}} No. {{numero_identificacion_negocio}}\nRepresentante: {{representante_negocio}}',
  '1. MODALIDAD CONTRATADA\n{{check_tienda}} Tienda\n{{check_directorio}} Directorio\n{{check_tienda_directorio}} Tienda + Directorio',
  '2. MARKETPLACE\nComisión BINGO+: {{comision_marketplace}} %\nBase de cálculo: Valor de la venta, sin impuestos\nÁmbito: Exclusivamente ventas de productos realizadas mediante el Marketplace BINGO+\nComisión sobre servicios: 0 %',
  '3. DIRECTORIO\nPlan Directorio: {{plan_directorio}}\nPeriodicidad: Mensual, a partir de la finalización del período de prueba o del período cubierto por el cupón redimido, según corresponda\nÁmbito: El fee corresponde exclusivamente a la participación de EL NEGOCIO en el Directorio',
  '4. LIQUIDACIÓN\nPeriodicidad: Quincenal\nMedio de pago: Depósito bancario o transferencia bancaria\nBanco: {{banco}}\nTipo de cuenta: {{tipo_cuenta}}\nNúmero de cuenta: {{numero_cuenta}}\nTitular: {{titular_cuenta}}',
  '5. VIGENCIA DEL ANEXO\nEl presente Anexo Comercial entrará en vigencia desde el {{fecha_vigencia}}. Cualquier modificación deberá ser aceptada por EL NEGOCIO mediante el mecanismo establecido por BINGO+ para tal efecto.',
  'BINGO+\n{{representante_legal_bingoplus}}\nRepresentante Legal\n{{razon_social_bingoplus}}\nEL NEGOCIO\n{{representante_negocio}}\n{{calidad_representante_negocio}},\n{{razon_social_negocio}}',
].join('\n\n');

export const DEFAULT_RIDER_CONTRACT_TEMPLATE = [
  'CLÁUSULA PRIMERA — OBJETO. Mediante el presente contrato, BINGO+ concede al Rider acceso a su plataforma tecnológica para recibir y ejecutar entregas de pedidos a través de la aplicación BINGO+ Rider, en los términos y condiciones aquí establecidos.',
  'CLÁUSULA SEGUNDA — TARIFAS, COMISIÓN Y RETENCIÓN. La tarifa de cada entrega la calcula BINGO+ según su fórmula vigente (tarifa mínima según franja horaria, distancia recorrida, tiempo y demanda). Sobre esa tarifa, BINGO+ retiene una comisión del {{comision_bingo}}%. Sobre el monto restante, BINGO+ retiene además un {{retencion_impuesto}}% en concepto de impuestos, transfiriendo al Rider el valor neto resultante.',
  'CLÁUSULA TERCERA — OBLIGACIONES DEL RIDER. El Rider se compromete a mantener actualizada su información personal, de identificación y de vehículo, a ejecutar las entregas aceptadas dentro de tiempos razonables y con el debido cuidado de los productos transportados, y a cumplir con la normativa de tránsito aplicable.',
  'CLÁUSULA CUARTA — OBLIGACIONES DE BINGO+. BINGO+ se compromete a mantener disponible la plataforma con niveles razonables de servicio, a transferir al Rider el valor neto de cada entrega completada conforme a los plazos establecidos, y a brindar soporte razonable durante la vigencia del contrato.',
  'CLÁUSULA QUINTA — VIGENCIA Y TERMINACIÓN. El presente contrato entra en vigencia en la fecha de su firma digital y se mantendrá vigente hasta que cualquiera de las partes lo termine mediante notificación escrita con al menos 30 días de anticipación, sin perjuicio de las obligaciones ya generadas.',
  'CLÁUSULA SEXTA — CONFIDENCIALIDAD Y DATOS PERSONALES. Ambas partes se obligan a mantener confidencialidad sobre la información comercial intercambiada y a tratar los datos personales de los usuarios conforme a la normativa de protección de datos aplicable.',
  'CLÁUSULA SÉPTIMA — VALIDEZ DE LA FIRMA DIGITAL. Las partes reconocen y aceptan que la firma digital consignada en este documento, junto con el identificador único de contrato y la dirección IP registrada al momento de la firma, constituyen prueba suficiente de la manifestación de voluntad y aceptación de los términos aquí descritos.',
].join('\n\n');

/**
 * Admin-editable contract template text (append-only, latest wins — same shape as
 * PricingConfigService). ContractsService/RiderContractsService read the latest template at
 * contract-GENERATION time and substitute its {{...}} placeholder tokens with that business/
 * rider's actual live figures; the result is frozen onto the contract row itself, so editing the
 * template here never changes a contract someone already signed (see BusinessContract.contractText/
 * RiderContract.contractText).
 */
@Injectable()
export class ContractTemplateService {
  constructor(private readonly prisma: PrismaService) {}

  async get(type: ContractTemplateType): Promise<string> {
    const row = await this.prisma.contractTemplate.findFirst({ where: { type }, orderBy: { createdAt: 'desc' } });
    if (row) return row.content;
    return type === ContractTemplateType.BUSINESS ? DEFAULT_BUSINESS_CONTRACT_TEMPLATE : DEFAULT_RIDER_CONTRACT_TEMPLATE;
  }

  async set(type: ContractTemplateType, content: string, updatedBy?: string): Promise<string> {
    await this.prisma.contractTemplate.create({ data: { type, content, updatedBy } });
    return content;
  }
}
